# Generated by Django 3.2 on 2021-05-05 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('end_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('periodicity', models.IntegerField(default=0, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('remind_employee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='UserActivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_code', models.CharField(max_length=200)),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 11, 27, 6, 81892, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 11, 27, 6, 81892, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('specialization', models.CharField(default=True, max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=True, max_length=20)),
                ('last_name', models.CharField(default=True, max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 5, 5, 11, 27, 6, 82891, tzinfo=utc))),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.institution')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=True, max_length=20)),
                ('last_name', models.CharField(default=True, max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.IntegerField(default=False)),
                ('remind_parent', models.BooleanField(default=False)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.activity')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.child')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=32)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.child')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.institution')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.employee'),
        ),
        migrations.AddField(
            model_name='activity',
            name='isntitution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.institution'),
        ),
    ]
