# Generated by Django 3.2 on 2021-05-05 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivate',
            options={'verbose_name': 'UserActivate', 'verbose_name_plural': 'UserActivations'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 45, 42, 411561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 45, 42, 411561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivate',
            name='activate_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='useractivate',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 14, 45, 42, 410561, tzinfo=utc)),
        ),
    ]
