# Generated by Django 3.2 on 2021-05-08 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20210505_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 10, 56, 24, 59353, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 10, 56, 24, 59353, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivate',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 10, 56, 24, 59353, tzinfo=utc)),
        ),
    ]
