# Generated by Django 3.2 on 2021-05-01 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20210501_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 17, 58, 39, 612811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 17, 58, 39, 612811, tzinfo=utc)),
        ),
    ]
